//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Ressources.Ressources", typeof(Ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string btnConnecter {
            get {
                return ResourceManager.GetString("btnConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string btnEnregistrer {
            get {
                return ResourceManager.GetString("btnEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string erreur_champsVides {
            get {
                return ResourceManager.GetString("erreur_champsVides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string erreur_loginFailed {
            get {
                return ResourceManager.GetString("erreur_loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string erreur_serveur {
            get {
                return ResourceManager.GetString("erreur_serveur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string groupboxInfos {
            get {
                return ResourceManager.GetString("groupboxInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string groupboxLivres {
            get {
                return ResourceManager.GetString("groupboxLivres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelAuteur {
            get {
                return ResourceManager.GetString("labelAuteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelIsbn {
            get {
                return ResourceManager.GetString("labelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelMotDePasse {
            get {
                return ResourceManager.GetString("labelMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelNbPages {
            get {
                return ResourceManager.GetString("labelNbPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelNomUtilisateur {
            get {
                return ResourceManager.GetString("labelNomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string labelTitre {
            get {
                return ResourceManager.GetString("labelTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string listColNom {
            get {
                return ResourceManager.GetString("listColNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string listHeader_isbn {
            get {
                return ResourceManager.GetString("listHeader_isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string listHeader_nom {
            get {
                return ResourceManager.GetString("listHeader_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string listHeader_titre {
            get {
                return ResourceManager.GetString("listHeader_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ERREUR.
        /// </summary>
        public static string textBlockTheme {
            get {
                return ResourceManager.GetString("textBlockTheme", resourceCulture);
            }
        }
    }
}
