//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Ressources.Ressources", typeof(Ressources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string btnConnecter {
            get {
                return ResourceManager.GetString("btnConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string btnEnregistrer {
            get {
                return ResourceManager.GetString("btnEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string erreur_champsVides {
            get {
                return ResourceManager.GetString("erreur_champsVides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string erreur_loginFailed {
            get {
                return ResourceManager.GetString("erreur_loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string erreur_serveur {
            get {
                return ResourceManager.GetString("erreur_serveur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string groupboxInfos {
            get {
                return ResourceManager.GetString("groupboxInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string groupboxLivres {
            get {
                return ResourceManager.GetString("groupboxLivres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelAuteur {
            get {
                return ResourceManager.GetString("labelAuteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelIsbn {
            get {
                return ResourceManager.GetString("labelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelMotDePasse {
            get {
                return ResourceManager.GetString("labelMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelNbPages {
            get {
                return ResourceManager.GetString("labelNbPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelNomUtilisateur {
            get {
                return ResourceManager.GetString("labelNomUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string labelTitre {
            get {
                return ResourceManager.GetString("labelTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string listColNom {
            get {
                return ResourceManager.GetString("listColNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string listHeader_isbn {
            get {
                return ResourceManager.GetString("listHeader_isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string listHeader_nom {
            get {
                return ResourceManager.GetString("listHeader_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string listHeader_titre {
            get {
                return ResourceManager.GetString("listHeader_titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string msg_loginReussi {
            get {
                return ResourceManager.GetString("msg_loginReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string msg_modifReussi {
            get {
                return ResourceManager.GetString("msg_modifReussi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #ERREUR.
        /// </summary>
        public static string textBlockTheme {
            get {
                return ResourceManager.GetString("textBlockTheme", resourceCulture);
            }
        }
    }
}
